# Generated by Django 4.2.1 on 2023-05-31 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CidadesAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_ibge", models.IntegerField()),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                (
                    "Usuario",
                    models.ManyToManyField(
                        related_name="cidades_atendidas", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
