# Generated by Django 4.2.1 on 2023-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="porcentagem_comissao",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_banheiro",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_cozinha",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_minimo",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_outros",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_quarto",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_quintal",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="service",
            name="valor_sala",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
